### ISSUE TITLE
Nicolo's TODO list

### ISSUE THREAD

**Issue by Nicogene** [robotology-playground/Robust-View-Graph-SLAM#3]
- [x] Implement a class for managing the user's choice of detector, descriptor and matcher(and relative parameters) through configuration files
- [x] Implement multithreading part 1: launch the process of every couple of images on different threads. Feature matching 2by2 (simplest case). 
  - Parallel acquisition+analysis(First commit of multithreadingPart1 branch) not convenient for the race condition on the counter access.
  - Only parallel analysis(Second commit of  multithreadingPart2 branch): DONE the problem was linked to the fact that if you define a thread in a loop you serialize the execution.
- [x] Implement multithreading part 2: on different threads find features of each image acquired and then match with the first frame, then change reference frame and repeat: DONE, every 20 frames changes the reference frame (multithreadingPart2 branch).
- [x] Add the check for ncams, it has to be multiple of 2 (in master and multithreading both)

**Comment by Tariq-Abuhashim** [comment]
Ok, this looks good, I will follow the progress.
Thanks.
